#pragma once

#include <stdint.h>
#include <array>
#include <string>

namespace fig::gui
{
	enum class Color : uint32_t
	{
		Undefined,
		Debug,
		Debug2,
		Debug3,
		Opaque,
		Transparent,
		White,
		Gray,
		Black,
		Red,
		Green,
		Blue,
		DarkGray,
		AppForeground,
		AppBackground,
		Accent,
		TextBoxSelectionForeground,
		TextBoxSelectionBackground,
		TextBoxSelectionBackgroundInactive,
		Border,
		BorderDisabled,
		BorderSelected,
		DisabledForeground,
		DisabledBackground,
		SidePanelForeground,
		SidePanelBackground,
		SidePanelGradient,
		TextBoxForeground,
		TextBoxBackground,
		TextBoxForegroundDisabled,
		TextBoxBackgroundDisabled,
		TextBoxScrollBar,
		PanelForeground,
		PanelBackground,
		PanelBackgroundHover,
		StatusBarForeground,
		StatusBarBackground,
		Icon,
		IconDisabled,
		Label,
		DisabledLabel,
		HintText,
		CheckBoxBackground,
		CheckBoxBackgroundPressed,
		SelectedControlBorder,
		SliderBackground,
		SliderThumb,
		SliderFill,
		ProgressBarFill,
		ScrollBar,

		MenuForeground,
		MenuForegroundDisabled,
		MenuBackground,
		MenuBorder,
		MenuItemHover,
		MenuItemPressed,
		CardShadow,

		MessageForeground,
		MessageBorderDefault,
		MessageBackgroundDefault,
		MessageBorderBlue,
		MessageBackgroundBlue,
		MessageBorderPink,
		MessageBackgroundPink,
		MessageBorderGreen,
		MessageBackgroundGreen,
		MessageBorderYellow,
		MessageBackgroundYellow,
		MessageBorderRed,
		MessageBackgroundRed,
		MessageBorderTeal,
		MessageBackgroundTeal,
		MessageBorderPurple,
		MessageBackgroundPurple,
		MessageBorderBrown,
		MessageBackgroundBrown,
		MessageBorderNavy,
		MessageBackgroundNavy,

		ButtonDefaultForeground,
		ButtonDefaultBackground,
		ButtonDefaultBorder,
		ButtonHoverForeground,
		ButtonHoverBackground,
		ButtonHoverBorder,
		ButtonPressedForeground,
		ButtonPressedBackground,
		ButtonPressedBorder,

		SidePanelButtonDefaultForeground,
		SidePanelButtonDefaultBackground,
		SidePanelButtonHoverForeground,
		SidePanelButtonHoverBackground,
		SidePanelButtonPressedForeground,
		SidePanelButtonPressedBackground,

		SaveButtonDefaultForeground,
		SaveButtonDefaultBackground,
		SaveButtonDefaultBorder,
		SaveButtonHoverForeground,
		SaveButtonHoverBackground,
		SaveButtonHoverBorder,
		SaveButtonPressedForeground,
		SaveButtonPressedBackground,
		SaveButtonPressedBorder,

		PlayButtonDefaultForeground,
		PlayButtonDefaultBackground,
		PlayButtonHoverForeground,
		PlayButtonHoverBackground,
		PlayButtonPressedForeground,
		PlayButtonPressedBackground,

		DisabledButtonForeground,
		DisabledButtonBackground,
		DisabledButtonBorder,
		GenderTagMale,
		GenderTagFemale,
		GenderTagOther,
		TagNew,

		Count,
	};
	
	constexpr auto ColorNameMapping = std::array<std::pair<Color, std::string_view>, static_cast<size_t>(Color::Count)> {
		std::pair { Color::AppForeground,						"App.Foreground" },
		std::pair { Color::AppBackground,						"App.Background" },
		std::pair { Color::Accent,								"App.Accent" },
		std::pair { Color::SidePanelForeground,					"SidePanel.Foreground" },
		std::pair { Color::SidePanelBackground,					"SidePanel.Background" },
		std::pair { Color::SidePanelGradient,					"SidePanel.Gradient" },
		std::pair { Color::Border,								"Border" },
		std::pair { Color::BorderDisabled,						"Border.Disabled" },
		std::pair { Color::BorderSelected,						"Border.Highlighted" },
		std::pair { Color::Icon,								"Icon" },
		std::pair { Color::IconDisabled,						"Icon.Disabled" },
		std::pair { Color::TextBoxForeground,					"TextBox.Foreground" },
		std::pair { Color::TextBoxBackground,					"TextBox.Background" },
		std::pair { Color::TextBoxForegroundDisabled,			"TextBox.Foreground.Disabled" },
		std::pair { Color::TextBoxBackgroundDisabled,			"TextBox.Background.Disabled" },
		std::pair { Color::TextBoxSelectionForeground,			"TextBox.Selection.Foreground" },
		std::pair { Color::TextBoxSelectionBackground,			"TextBox.Selection.Background" },
		std::pair { Color::TextBoxSelectionBackgroundInactive,	"TextBox.Selection.Background.Inactive" },
		std::pair { Color::TextBoxScrollBar,					"TextBox.ScrollBar" },
		std::pair { Color::PanelForeground,						"Panel.Foreground" },
		std::pair { Color::PanelBackground,						"Panel.Background" },
		std::pair { Color::PanelBackgroundHover,				"Panel.Background.Hover" },
		std::pair { Color::StatusBarForeground,					"StatusBar.Foreground" },
		std::pair { Color::StatusBarBackground,					"StatusBar.Background" },
		std::pair { Color::CheckBoxBackground,					"CheckBox.Background" },
		std::pair { Color::CheckBoxBackgroundPressed,			"CheckBox.Background.Pressed" },
		std::pair { Color::SelectedControlBorder,				"Control.Selected.Border" },
		std::pair { Color::DisabledForeground,					"Control.Foreground.Disabled" },
		std::pair { Color::DisabledBackground,					"Control.Background.Disabled" },
		std::pair { Color::ScrollBar,							"ScrollBar" },
		std::pair { Color::SliderBackground,					"Slider.Background" },
		std::pair { Color::SliderThumb,							"Slider.Thumb" },
		std::pair { Color::SliderFill,							"Slider.Fill" },
		std::pair { Color::ProgressBarFill,						"ProgressBar.Fill" },
		std::pair { Color::Label,								"Label" },
		std::pair { Color::DisabledLabel,						"Label.Disabled" },
		std::pair { Color::HintText,							"HintText" },
		std::pair { Color::MenuBackground,						"Menu.Background" },
		std::pair { Color::MenuForeground,						"Menu.Foreground" },
		std::pair { Color::MenuForegroundDisabled,				"Menu.Foreground.Disabled" },
		std::pair { Color::MenuBorder,							"Menu.Border" },
		std::pair { Color::MenuItemHover,						"Menu.Item.Hover" },
		std::pair { Color::MenuItemPressed,						"Menu.Item.Pressed" },
		std::pair { Color::CardShadow,							"Card.Shadow" },
		std::pair { Color::MessageForeground,					"Message.Foreground" },
		std::pair { Color::MessageBorderDefault,				"Message.Default.Border" },
		std::pair { Color::MessageBackgroundDefault,			"Message.Default.Background" },
		std::pair { Color::MessageBorderBlue,					"Message.Blue.Border" },
		std::pair { Color::MessageBackgroundBlue,				"Message.Blue.Background" },
		std::pair { Color::MessageBorderPink,					"Message.Pink.Border" },
		std::pair { Color::MessageBackgroundPink,				"Message.Pink.Background" },
		std::pair { Color::MessageBorderGreen,					"Message.Green.Border" },
		std::pair { Color::MessageBackgroundGreen,				"Message.Green.Background" },
		std::pair { Color::MessageBorderYellow,					"Message.Yellow.Border" },
		std::pair { Color::MessageBackgroundYellow,				"Message.Yellow.Background" },
		std::pair { Color::MessageBorderRed,					"Message.Red.Border" },
		std::pair { Color::MessageBackgroundRed,				"Message.Red.Background" },
		std::pair { Color::MessageBorderTeal,					"Message.Teal.Border" },
		std::pair { Color::MessageBackgroundTeal,				"Message.Teal.Background" },
		std::pair { Color::MessageBorderPurple,					"Message.Purple.Border" },
		std::pair { Color::MessageBackgroundPurple,				"Message.Purple.Background" },
		std::pair { Color::MessageBorderBrown,					"Message.Brown.Border" },
		std::pair { Color::MessageBackgroundBrown,				"Message.Brown.Background" },
		std::pair { Color::MessageBorderNavy,					"Message.Navy.Border" },
		std::pair { Color::MessageBackgroundNavy,				"Message.Navy.Background" },
		std::pair { Color::ButtonDefaultForeground,				"Button.Default.Foreground" },
		std::pair { Color::ButtonDefaultBackground,				"Button.Default.Background" },
		std::pair { Color::ButtonDefaultBorder,					"Button.Default.Border" },
		std::pair { Color::ButtonHoverForeground,				"Button.Hover.Foreground" },
		std::pair { Color::ButtonHoverBackground,				"Button.Hover.Background" },
		std::pair { Color::ButtonHoverBorder,					"Button.Hover.Border" },
		std::pair { Color::ButtonPressedForeground,				"Button.Pressed.Foreground" },
		std::pair { Color::ButtonPressedBackground,				"Button.Pressed.Background" },
		std::pair { Color::ButtonPressedBorder,					"Button.Pressed.Border" },
		std::pair { Color::SidePanelButtonDefaultForeground,	"SidePanelButton.Default.Foreground" },
		std::pair { Color::SidePanelButtonDefaultBackground,	"SidePanelButton.Default.Background" },
		std::pair { Color::SidePanelButtonHoverForeground,		"SidePanelButton.Hover.Foreground" },
		std::pair { Color::SidePanelButtonHoverBackground,		"SidePanelButton.Hover.Background" },
		std::pair { Color::SidePanelButtonPressedForeground,	"SidePanelButton.Pressed.Foreground" },
		std::pair { Color::SidePanelButtonPressedBackground,	"SidePanelButton.Pressed.Background" },
		std::pair { Color::SaveButtonDefaultForeground,			"SaveButton.Default.Foreground" },
		std::pair { Color::SaveButtonDefaultBackground,			"SaveButton.Default.Background" },
		std::pair { Color::SaveButtonDefaultBorder,				"SaveButton.Default.Border" },
		std::pair { Color::SaveButtonHoverForeground,			"SaveButton.Hover.Foreground" },
		std::pair { Color::SaveButtonHoverBackground,			"SaveButton.Hover.Background" },
		std::pair { Color::SaveButtonHoverBorder,				"SaveButton.Hover.Border" },
		std::pair { Color::SaveButtonPressedForeground,			"SaveButton.Pressed.Foreground" },
		std::pair { Color::SaveButtonPressedBackground,			"SaveButton.Pressed.Background" },
		std::pair { Color::SaveButtonPressedBorder,				"SaveButton.Pressed.Border" },
		std::pair { Color::PlayButtonDefaultForeground,			"PlayButton.Default.Foreground" },
		std::pair { Color::PlayButtonDefaultBackground,			"PlayButton.Default.Background" },
		std::pair { Color::PlayButtonHoverForeground,			"PlayButton.Hover.Foreground" },
		std::pair { Color::PlayButtonHoverBackground,			"PlayButton.Hover.Background" },
		std::pair { Color::PlayButtonPressedForeground,			"PlayButton.Pressed.Foreground" },
		std::pair { Color::PlayButtonPressedBackground,			"PlayButton.Pressed.Background" },
		std::pair { Color::DisabledButtonForeground,			"DisabledButton.Foreground" },
		std::pair { Color::DisabledButtonBackground,			"DisabledButton.Background" },
		std::pair { Color::DisabledButtonBorder,				"DisabledButton.Border" },

		std::pair { Color::Debug,								"Debug" },
		std::pair { Color::Debug2,								"Debug2" },
		std::pair { Color::Debug3,								"Debug3" },
		std::pair { Color::Opaque,								"Opaque" },
		std::pair { Color::Transparent,							"Transparent" },
		std::pair { Color::White,								"White" },
		std::pair { Color::Gray,								"Gray" },
		std::pair { Color::Black,								"Black" },
		std::pair { Color::Red,									"Red" },
		std::pair { Color::Green,								"Green" },
		std::pair { Color::Blue,								"Blue" },
		std::pair { Color::DarkGray,							"DarkGray" },
		std::pair { Color::GenderTagMale,						"Tag.Gender.Male" },
		std::pair { Color::GenderTagFemale,						"Tag.Gender.Female" },
		std::pair { Color::GenderTagOther,						"Tag.Gender.Other" },
		std::pair { Color::TagNew,								"Tag.New" },
	};
}